running_func_all_ages_3D<-function(batch.of.No.individual,
                                   input.state.var.list,
                                   All.Temp.grid.current.in.day,
                                   All.Temp.grid.next.in.day,
                                   All.MIC.grid.current.in.day,
                                   All.MIC.grid.next.in.day,
                                   All.MES.grid.current.in.day,
                                   All.MES.grid.next.in.day,
                                   All.uo.grid.current.in.day,
                                   All.uo.grid.next.in.day,
                                   All.vo.grid.current.in.day,
                                   All.vo.grid.next.in.day,
                                   All.wo.grid.current.in.day,
                                   All.wo.grid.next.in.day,
                                   All.rho.grid.current.in.day,
                                   All.rho.grid.next.in.day,
                                   All.Sal.grid.current.in.day,
                                   All.Sal.grid.next.in.day,
                                   All.sd.grid.current.in.day,
                                   All.sd.grid.next.in.day,
                                   input.func,
                                   input.data.location,
                                   input.stoke.drift,
                                   timestep,
                                   parms.total,
                                   individual_per_core,
                                   current_month){
  
  input.state.var.age.0<-input.state.var.list[[1]]
  input.state.var.age.1<-input.state.var.list[[2]]  
  input.state.var.age.2<-input.state.var.list[[3]]
  input.state.var.age.3<-input.state.var.list[[4]]
  input.state.var.age.4<-input.state.var.list[[5]]
  
  results.timestep.age.0<-running_func_age_0_4_3D(batch.of.No.individual = batch.of.No.individual,
                                                  input.state.var.age.dif = input.state.var.age.0,
                                                  All.Temp.grid.current.in.day = All.Temp.grid.current.in.day,
                                                  All.Temp.grid.next.in.day = All.Temp.grid.next.in.day,
                                                  All.MIC.grid.current.in.day = All.MIC.grid.current.in.day,
                                                  All.MIC.grid.next.in.day = All.MIC.grid.next.in.day,
                                                  All.MES.grid.current.in.day = All.MES.grid.current.in.day,
                                                  All.MES.grid.next.in.day = All.MES.grid.next.in.day,
                                                  All.uo.grid.current.in.day = All.uo.grid.current.in.day,
                                                  All.uo.grid.next.in.day = All.uo.grid.next.in.day,
                                                  All.vo.grid.current.in.day = All.vo.grid.current.in.day,
                                                  All.vo.grid.next.in.day = All.vo.grid.next.in.day,
                                                  All.wo.grid.current.in.day = All.wo.grid.current.in.day,
                                                  All.wo.grid.next.in.day = All.wo.grid.next.in.day,
                                                  All.rho.grid.current.in.day = All.rho.grid.current.in.day,
                                                  All.rho.grid.next.in.day = All.rho.grid.next.in.day,
                                                  All.Sal.grid.current.in.day = All.Sal.grid.current.in.day,
                                                  All.Sal.grid.next.in.day = All.Sal.grid.next.in.day,
                                                  All.sd.grid.current.in.day = All.sd.grid.current.in.day,
                                                  All.sd.grid.next.in.day = All.sd.grid.next.in.day,
                                                  input.func = input.func,
                                                  input.data.location = input.data.location,
                                                  input.stoke.drift = input.stoke.drift,
                                                  timestep = timestep,
                                                  parms.total = parms.total,
                                                  individual_per_core = individual_per_core,
                                                  current_month = current_month)
  
  results.timestep.age.1<-running_func_age_0_4_3D(batch.of.No.individual = batch.of.No.individual,
                                                  input.state.var.age.dif = input.state.var.age.1,
                                                  All.Temp.grid.current.in.day = All.Temp.grid.current.in.day,
                                                  All.Temp.grid.next.in.day = All.Temp.grid.next.in.day,
                                                  All.MIC.grid.current.in.day = All.MIC.grid.current.in.day,
                                                  All.MIC.grid.next.in.day = All.MIC.grid.next.in.day,
                                                  All.MES.grid.current.in.day = All.MES.grid.current.in.day,
                                                  All.MES.grid.next.in.day = All.MES.grid.next.in.day,
                                                  All.uo.grid.current.in.day = All.uo.grid.current.in.day,
                                                  All.uo.grid.next.in.day = All.uo.grid.next.in.day,
                                                  All.vo.grid.current.in.day = All.vo.grid.current.in.day,
                                                  All.vo.grid.next.in.day = All.vo.grid.next.in.day,
                                                  All.wo.grid.current.in.day = All.wo.grid.current.in.day,
                                                  All.wo.grid.next.in.day = All.wo.grid.next.in.day,
                                                  All.rho.grid.current.in.day = All.rho.grid.current.in.day,
                                                  All.rho.grid.next.in.day = All.rho.grid.next.in.day,
                                                  All.Sal.grid.current.in.day = All.Sal.grid.current.in.day,
                                                  All.Sal.grid.next.in.day = All.Sal.grid.next.in.day,
                                                  All.sd.grid.current.in.day = All.sd.grid.current.in.day,
                                                  All.sd.grid.next.in.day = All.sd.grid.next.in.day,
                                                  input.func = input.func,
                                                  input.data.location = input.data.location,
                                                  input.stoke.drift = input.stoke.drift,
                                                  timestep = timestep,
                                                  parms.total = parms.total,
                                                  individual_per_core = individual_per_core,
                                                  current_month = current_month)
  
  results.timestep.age.2<-running_func_age_0_4_3D(batch.of.No.individual = batch.of.No.individual,
                                                  input.state.var.age.dif = input.state.var.age.2,
                                                  All.Temp.grid.current.in.day = All.Temp.grid.current.in.day,
                                                  All.Temp.grid.next.in.day = All.Temp.grid.next.in.day,
                                                  All.MIC.grid.current.in.day = All.MIC.grid.current.in.day,
                                                  All.MIC.grid.next.in.day = All.MIC.grid.next.in.day,
                                                  All.MES.grid.current.in.day = All.MES.grid.current.in.day,
                                                  All.MES.grid.next.in.day = All.MES.grid.next.in.day,
                                                  All.uo.grid.current.in.day = All.uo.grid.current.in.day,
                                                  All.uo.grid.next.in.day = All.uo.grid.next.in.day,
                                                  All.vo.grid.current.in.day = All.vo.grid.current.in.day,
                                                  All.vo.grid.next.in.day = All.vo.grid.next.in.day,
                                                  All.wo.grid.current.in.day = All.wo.grid.current.in.day,
                                                  All.wo.grid.next.in.day = All.wo.grid.next.in.day,
                                                  All.rho.grid.current.in.day = All.rho.grid.current.in.day,
                                                  All.rho.grid.next.in.day = All.rho.grid.next.in.day,
                                                  All.Sal.grid.current.in.day = All.Sal.grid.current.in.day,
                                                  All.Sal.grid.next.in.day = All.Sal.grid.next.in.day,
                                                  All.sd.grid.current.in.day = All.sd.grid.current.in.day,
                                                  All.sd.grid.next.in.day = All.sd.grid.next.in.day,
                                                  input.func = input.func,
                                                  input.data.location = input.data.location,
                                                  input.stoke.drift = input.stoke.drift,
                                                  timestep = timestep,
                                                  parms.total = parms.total,
                                                  individual_per_core = individual_per_core,
                                                  current_month = current_month)
  
  results.timestep.age.3<-running_func_age_0_4_3D(batch.of.No.individual = batch.of.No.individual,
                                                  input.state.var.age.dif = input.state.var.age.3,
                                                  All.Temp.grid.current.in.day = All.Temp.grid.current.in.day,
                                                  All.Temp.grid.next.in.day = All.Temp.grid.next.in.day,
                                                  All.MIC.grid.current.in.day = All.MIC.grid.current.in.day,
                                                  All.MIC.grid.next.in.day = All.MIC.grid.next.in.day,
                                                  All.MES.grid.current.in.day = All.MES.grid.current.in.day,
                                                  All.MES.grid.next.in.day = All.MES.grid.next.in.day,
                                                  All.uo.grid.current.in.day = All.uo.grid.current.in.day,
                                                  All.uo.grid.next.in.day = All.uo.grid.next.in.day,
                                                  All.vo.grid.current.in.day = All.vo.grid.current.in.day,
                                                  All.vo.grid.next.in.day = All.vo.grid.next.in.day,
                                                  All.wo.grid.current.in.day = All.wo.grid.current.in.day,
                                                  All.wo.grid.next.in.day = All.wo.grid.next.in.day,
                                                  All.rho.grid.current.in.day = All.rho.grid.current.in.day,
                                                  All.rho.grid.next.in.day = All.rho.grid.next.in.day,
                                                  All.Sal.grid.current.in.day = All.Sal.grid.current.in.day,
                                                  All.Sal.grid.next.in.day = All.Sal.grid.next.in.day,
                                                  All.sd.grid.current.in.day = All.sd.grid.current.in.day,
                                                  All.sd.grid.next.in.day = All.sd.grid.next.in.day,
                                                  input.func = input.func,
                                                  input.data.location = input.data.location,
                                                  input.stoke.drift = input.stoke.drift,
                                                  timestep = timestep,
                                                  parms.total = parms.total,
                                                  individual_per_core = individual_per_core,
                                                  current_month = current_month)
  
  results.timestep.age.4<-running_func_age_0_4_3D(batch.of.No.individual = batch.of.No.individual,
                                                  input.state.var.age.dif = input.state.var.age.4,
                                                  All.Temp.grid.current.in.day = All.Temp.grid.current.in.day,
                                                  All.Temp.grid.next.in.day = All.Temp.grid.next.in.day,
                                                  All.MIC.grid.current.in.day = All.MIC.grid.current.in.day,
                                                  All.MIC.grid.next.in.day = All.MIC.grid.next.in.day,
                                                  All.MES.grid.current.in.day = All.MES.grid.current.in.day,
                                                  All.MES.grid.next.in.day = All.MES.grid.next.in.day,
                                                  All.uo.grid.current.in.day = All.uo.grid.current.in.day,
                                                  All.uo.grid.next.in.day = All.uo.grid.next.in.day,
                                                  All.vo.grid.current.in.day = All.vo.grid.current.in.day,
                                                  All.vo.grid.next.in.day = All.vo.grid.next.in.day,
                                                  All.wo.grid.current.in.day = All.wo.grid.current.in.day,
                                                  All.wo.grid.next.in.day = All.wo.grid.next.in.day,
                                                  All.rho.grid.current.in.day = All.rho.grid.current.in.day,
                                                  All.rho.grid.next.in.day = All.rho.grid.next.in.day,
                                                  All.Sal.grid.current.in.day = All.Sal.grid.current.in.day,
                                                  All.Sal.grid.next.in.day = All.Sal.grid.next.in.day,
                                                  All.sd.grid.current.in.day = All.sd.grid.current.in.day,
                                                  All.sd.grid.next.in.day = All.sd.grid.next.in.day,
                                                  input.func = input.func,
                                                  input.data.location = input.data.location,
                                                  input.stoke.drift = input.stoke.drift,
                                                  timestep = timestep,
                                                  parms.total = parms.total,
                                                  individual_per_core = individual_per_core,
                                                  current_month = current_month)
  
  results.total<-list(results.timestep.age.0,
                      results.timestep.age.1,
                      results.timestep.age.2,
                      results.timestep.age.3,
                      results.timestep.age.4)
  
  return(results.total)
}